<?php
/**
 * @file
 * Openplus Layouts
 */


// Plugin definition.
$plugin = array(
  'title' => t('Openplus 33/66'),
  'icon' => 'openplus-33-66.png',
  'category' => t('Openplus Layouts'),
  'theme' => 'openplus_33_66',
  'css' => 'openplus-33-66.css',
  'admin css' => 'openplus-33-66.admin.css',
  'regions' => array(
    'openplus_33_66_left' => t('Left'),
    'openplus_33_66_right' => t('Right'),
    'openplus_33_66_top' => t('Top'),
    'openplus_33_66_bottom' => t('Bottom'),
  ),
);
