<?php
/**
 * @file
 * Openplus Layouts
 */


// Plugin definition.
$plugin = array(
  'title' => t('Openplus 66/33'),
  'icon' => 'openplus-66-33.png',
  'category' => t('Openplus Layouts'),
  'theme' => 'openplus_66_33',
  'css' => 'openplus-66-33.css',
  'admin css' => 'openplus-66-33.admin.css',
  'regions' => array(
    'openplus_66_33_left' => t('Left'),
    'openplus_66_33_leftbottom' => t('Left Bottom'),
    'openplus_66_33_right' => t('Right'),
    'openplus_66_33_top' => t('Top'),
    'openplus_66_33_bottom' => t('Bottom'),
  ),
);
